### ISSUE TITLE
docker-entrypoint.sh execution flag is lacking

### ISSUE THREAD

**Issue by AlexandreFenyo** [mitmproxy/docker-releases#10]
I get the following error message :

\# docker run --rm -it -p 8080:8080 mitmproxy/mitmproxy
exec: "docker-entrypoint.sh": executable file not found in $PATH

This is because when building the image from the Dockerfile, the file permissions of docker-entrypoint.sh in the image are just copied from the ones of the entrypoint file extracted from the git repository, and the permissions of this file in the git repository does not contain the executable flag :
\# git log --summary docker-entrypoint.sh | grep mode
 create mode 100644 alpine/docker-entrypoint.sh
It should contain 755, not 644.

To get the image working, just add the following line in the Dockerfile :
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
Add this line just after the line "COPY docker-entrypoint.sh /usr/local/bin/".

You can also change the mode of docker-entrypoint.sh in the git repository.

Sincerely

**Comment by mhils** [comment]
Fixed in 5e8a01fa4fb3b88f7ac66da2d193141c6bfcc6eb, thanks!

**Comment by AlexandreFenyo** [comment]
Thanks
