### ISSUE TITLE
mitmweb

### ISSUE THREAD

**Issue by luckymancvp** [mitmproxy/docker-releases#12]
Dear Team !

I can start mitmweb by running this command 
`docker run -d -it -p 8081:8081 -p 8080:8080 mitm mitmweb`

But I can not open web interface , because It looks like that mitmweb only listening localhost 127.0.0.1 

Is there any way to open web interface from anywhere ( not local )

**Comment by mhils** [comment]
Can you fix this with `--wiface 0.0.0.0`?

**Comment by luckymancvp** [comment]
you saved my life
