### ISSUE TITLE
Can't export flow neither to clipboard or file

### ISSUE THREAD

**Issue by Alexand** [mitmproxy/docker-releases#20]
I believe this is because of container permissions.

Steps to reproduce:

1) start MITM on docker:
``` bash
docker run --rm -it -v ~/.mitmproxy:/home/mitmproxy/.mitmproxy -p 9999:8080 mitmproxy/mitmproxy
```

2) Send any request to your proxy.

3) hit `Shift + C` to call the export menu, then for instance, hit `r` to export as curl . You'll get the message:
`Cannot copy data to clipboard. Save as file? (yes, no)`

4) hit `y` and enter any filename. You'll get: `permission denied`

**Comment by Kriechi** [comment]
Docker does not allow access to your host clipboard.
