### ISSUE TITLE
Create tagged image for 0.18.2

### ISSUE THREAD

**Issue by jeffcharles** [mitmproxy/docker-releases#9]
Can you please create a tagged image for version 0.18.2.

It should be as simple as creating as changing the `alpine/requirements.txt` file to:

```
mitmproxy==0.18.2
```

**Comment by mhils** [comment]
Thanks for letting us know! Seems like our release checklist did not include that yet (https://github.com/mitmproxy/mitmproxy/commit/39b24a5babed92084b16dd7ca349d55e86375cb1).
I'll push a new release ASAP.

**Comment by mhils** [comment]
Thanks again - 0.18.2 is building and should be up in a couple of minutes! :smiley:
